INSTRUMENT_NAMES = {
    1:	"Acoustic Grand Piano",
    2:	"Bright Acoustic Piano",
    3:	"Electric Grand Piano",
    4:	"Honky-tonk Piano",
    5:	"Electric Piano 1 (Rhodes Piano)",
    6:	"Electric Piano 2 (Chorused Piano)",
    7:	"Harpsichord",
    8:	"Clavinet",
    9:	"Celesta",
    10:	"Glockenspiel",
    11:	"Music Box",
    12:	"Vibraphone",
    13:	"Marimba",
    14:	"Xylophone",
    15:	"Tubular Bells",
    16:	"Dulcimer (Santur)",
    17:	"Drawbar Organ (Hammond)",
    18:	"Percussive Organ",
    19:	"Rock Organ",
    20:	"Church Organ",
    21:	"Reed Organ",
    22:	"Accordion (French)",
    23:	"Harmonica",
    24:	"Tango Accordion (Band neon)",
    25:	"Acoustic Guitar (nylon)",
    26:	"Acoustic Guitar (steel)",
    27:	"Electric Guitar (jazz)",
    28:	"Electric Guitar (clean)",
    29:	"Electric Guitar (muted)",
    30:	"Overdriven Guitar",
    31:	"Distortion Guitar",
    32:	"Guitar harmonics",
    33:	"Acoustic Bass",
    34:	"Electric Bass (fingered)",
    35:	"Electric Bass (picked)",
    36:	"Fretless Bass",
    37:	"Slap Bass 1",
    38:	"Slap Bass 2",
    39:	"Synth Bass 1",
    40:	"Synth Bass 2",
    41:	"Violin",
    42:	"Viola",
    43:	"Cello",
    44:	"Contrabass",
    45:	"Tremolo Strings",
    46:	"Pizzicato Strings",
    47:	"Orchestral Harp",
    48:	"Timpani",
    49:	"String Ensemble 1 (strings)",
    50:	"String Ensemble 2 (slow strings)",
    51:	"SynthStrings 1",
    52:	"SynthStrings 2",
    53:	"Choir Aahs",
    54:	"Voice Oohs",
    55:	"Synth Voice",
    56:	"Orchestra Hit",
    57:	"Trumpet",
    58:	"Trombone",
    59:	"Tuba",
    60:	"Muted Trumpet",
    61:	"French Horn",
    62:	"Brass Section",
    63:	"SynthBrass 1",
    64:	"SynthBrass 2",
    65:	"Soprano Sax",
    66:	"Alto Sax",
    67:	"Tenor Sax",
    68:	"Baritone Sax",
    69:	"Oboe",
    70:	"English Horn",
    71:	"Bassoon",
    72:	"Clarinet",
    73:	"Piccolo",
    74:	"Flute",
    75:	"Recorder",
    76:	"Pan Flute",
    77:	"Blown Bottle",
    78:	"Shakuhachi",
    79:	"Whistle",
    80:	"Ocarina",
    81:	"Lead 1 (square wave)",
    82:	"Lead 2 (sawtooth wave)",
    83:	"Lead 3 (calliope)",
    84:	"Lead 4 (chiffer)",
    85:	"Lead 5 (charang)",
    86:	"Lead 6 (voice solo)",
    87:	"Lead 7 (fifths)",
    88:	"Lead 8 (bass + lead)",
    89:	"Pad 1 (new age Fantasia)",
    90:	"Pad 2 (warm)",
    91:	"Pad 3 (polysynth)",
    92:	"Pad 4 (choir space voice)",
    93:	"Pad 5 (bowed glass)",
    94:	"Pad 6 (metallic pro)",
    95:	"Pad 7 (halo)",
    96:	"Pad 8 (sweep)",
    97:	"FX 1 (rain)",
    98:	"FX 2 (soundtrack)",
    99:	"FX 3 (crystal)",
    100:	"FX 4 (atmosphere)",
    101:	"FX 5 (brightness)",
    102:	"FX 6 (goblins)",
    103:	"FX 7 (echoes, drops)",
    104:	"FX 8 (sci-fi, star theme)",
    105:	"Sitar",
    106:	"Banjo",
    107:	"Shamisen",
    108:	"Koto",
    109:	"Kalimba",
    110:	"Bag pipe",
    111:	"Fiddle",
    112:	"Shanai",
    113:	"Tinkle Bell",
    114:	"Agogo",
    115:	"Steel Drums",
    116:	"Woodblock",
    117:	"Taiko Drum",
    118:	"Melodic Tom",
    119:	"Synth Drum",
    120:	"Reverse Cymbal",
    121:	"Guitar Fret Noise",
    122:	"Breath Noise",
    123:	"Seashore",
    124:	"Bird Tweet",
    125:	"Telephone Ring",
    126:	"Helicopter",
    127:	"Applause",
    128:	"Gunshot",
    }

GDC_INSTRUMENTS = (
    "_pause",
    "boom",
    "bruh",
    "bong",
    "💀",
    "👏",
    "🐶",
    "👽",
    "🔔",
    "💢",
    "💨",
    "🚫",
    "📲",
    "🌄",
    "🏏",
    "🤬",
    "🚨",
    "buzzer",
    "❗",
    "🦀",
    "e",
    "eight",
    "🍕",
    "🦢",
    "gun",
    "hitmarker",
    "👌",
    "whatsapp",
    "gnome",
    "💿",
    "🎉",
    "🎻",
    "pan",
    "slip",
    "whipcrack",
    "explosion",
    "oof",
    "subaluwa",
    "necoarc",
    "yoda",
    "hehehehaw",
    "granddad",
    "morshu",
    "stopposting",
    "21",
    "op",
    "SLAM",
    "americano",
    "smw_coin",
    "smw_1up",
    "smw_spinjump",
    "smw_stomp2",
    "smw_kick",
    "smw_stomp",
    "yahoo",
    "sm64_hurt",
    "bup",
    "thwomp",
    "sm64_painting",
    "smm_scream",
    "mariopaint_mario",
    "mariopaint_luigi",
    "smw_yoshi",
    "mariopaint_star",
    "mariopaint_flower",
    "mariopaint_gameboy",
    "mariopaint_dog",
    "mariopaint_cat",
    "mariopaint_swan",
    "mariopaint_baby",
    "mariopaint_plane",
    "mariopaint_car",
    "shaker",
    "🥁",
    "hammer",
    "🪘",
    "sidestick",
    "ride2",
    "buttonpop",
    "skipshot",
    "otto_on",
    "otto_off",
    "otto_happy",
    "otto_stress",
    "tab_sounds",
    "tab_rows",
    "tab_actions",
    "tab_decorations",
    "tab_rooms",
    "preecho",
    "tonk",
    "rdmistake",
    "samurai",
    "adofaikick",
    "midspin",
    "adofaicymbal",
    "cowbell",
    "karateman_throw",
    "karateman_offbeat",
    "karateman_hit",
    "karateman_bulb",
    "ook",
    "choruskid",
    "builttoscale",
    "perfectfail",
    "🌟",
    "hoenn",
    "🎺",
    "fnf_left",
    "fnf_down",
    "fnf_up",
    "fnf_right",
    "fnf_death",
    "megalovania",
    "🦴",
    "undertale_encounter",
    "undertale_hit",
    "undertale_crack",
    "toby",
    "gaster",
    "gdcrash",
    "gdcrash_orbs",
    "gd_coin",
    "gd_orbs",
    "gd_diamonds",
    "bwomp",
    "isaac_hurt",
    "isaac_dead",
    "isaac_mantle",
    "terraria_star",
    "terraria_pot",
    "terraria_reforge",
    "BABA",
    "YOU",
    "DEFEAT",
    "celeste_dash",
    "celeste_death",
    "celeste_spring",
    "celeste_diamond",
    "ultrainstinct",
    "flipnote",
    "amongus",
    "amongdrip",
    "amogus",
    "noteblock_harp",
    "noteblock_bass",
    "noteblock_snare",
    "noteblock_click",
    "noteblock_bell",
    "noteblock_chime",
    "noteblock_banjo",
    "noteblock_pling",
    "noteblock_xylophone",
    "noteblock_bit",
    "minecraft_explosion",
    "minecraft_bell",
    )
